"""
Program to view Wine Services Data
Author: Jack d'Entremont
"""
### Update following dictionaries as SKUs are added to Wine Services or Guidances change
guidance6000ml = {'Robert Mondavi, Reserve To Kalon, Cabernet Sauvignon': '$1040',
                  'Robert Mondavi, Napa, Cabernet Sauvignon': '$90',
                  'Schrader, GIII Beckstoffer Georges III, Cabernet Sauvignon': '$3000'}

guidance5000ml = {'Robert Mondavi, Carneros, Pinot Noir Reserve': '$160'}

guidance3000ml = {'Ruffino, Modus': '$103',
                  'Robert Mondavi, Napa, Cabernet Sauvignon': '$150',
                  'Robert Mondavi, Reserve To Kalon, Cabernet Sauvignon': '$520',
                  'Schrader, GIII Beckstoffer Georges III, Cabernet Sauvignon': '$1500'}

guidance1500ml = {'The Prisoner': '$60',
                'The Prisoner, Saldo, Zinfandel': '$60',
                'The Prisoner, Red Blend': '$60',
                'The Prisoner, Cabernet Sauvignon': '$62',
                'Ruffino, Chianti Classico, Riserva Ducale': '$12',
                'Ruffino, Modus': '$46',
                'Ruffino, Romitorio Santedame': '$90',
                'Ruffino, Toscana Cabreo Borgo': '$63',
                'Robert Mondavi, Napa, Cabernet Sauvignon': '$60',
                'Robert Mondavi, Reserve To Kalon, Cabernet Sauvignon': '$260',
                'Robert Mondavi, To Kalon, Cabernet Sauvignon': '$260',
                'Robert Mondavi, Stags Leap District, Cabernet Sauvignon': '$260',
                'Robert Mondavi, The Estates, Oakville, Cabernet Sauvignon': '$90',
                'Schrader, Old Sparky, Cabernet Sauvignon': '$750',
                'Schrader, Beckstoffer To Kalon, Cabernet Sauvignon': '$750',
                'Schrader, Colesworthy, Cabernet Sauvignon': '$750',
                'Schrader, Beckstoffer Las Piedras, Cabernet Sauvignon': '$750',
                'Schrader, LPV Beckstoffer Las Piedras Vineyard, Cabernet Sauvignon': '$750',
                'Schrader, RBS Beckstoffer To Kalon, Cabernet Sauvignon': '$750',
                'Double Diamond, Mayacamas': '$127',
                'Double Diamond, Oakville, Napa Valley': '$127'}

guidance750ml = {'The Prisoner': '$30',
               'The Prisoner, Saldo, Zinfandel': '$20',
               'The Prisoner, Unshackled, Chardonnay': '$24',
               'The Prisoner, Cabernet Sauvignon': '$31',
               'The Prisoner, Blindfold, White': '$20',
               'The Prisoner, Red Blend': '$90',
               'The Prisoner, Chardonnay': '$24',
               'The Prisoner, Unshackled, Cabernet Sauvignon': '$15',
               'The Prisoner, Pinot Noir': '$28',
               'The Prisoner, Saldo, Chenin Blanc': '$16',
               'The Prisoner, Blindfold': '$20',
               'The Prisoner, Cuttings Cabernet Sauvignon': '$31',
               'The Prisoner, Thorn': '$30',
               'The Prisoner, Derange': '$30',
               'The Prisoner, The Snitch, Chardonnay': '$24',
               'The Prisoner, Eternally Silenced': '$30',
               'Ruffino, Modus': '$18',
               'Ruffino, Chianti Classico, Riserva Ducale': '$9.75',
               'Ruffino, Il Ducale': '$11',
               'Ruffino, Romitorio Santedame': '$45',
               'Ruffino, Toscana Cabreo Borgo': '$55',
               'Robert Mondavi, Napa, Chardonnay': '$22',
               'Robert Mondavi, Napa, Cabernet Sauvignon': '$27',
               'Robert Mondavi, Napa, Cabernet Franc': '$52',
               'Robert Mondavi, Napa, Merlot': '$24',
               'Robert Mondavi, Napa, Pinot Noir': '$24',
               'Robert Mondavi, Napa, Pinot noir': '$24',
               'Robert Mondavi, Napa, Zinfandel': '$52',
               'Robert Mondavi, Reserve To Kalon, Cabernet Sauvignon': '$113',
               'Robert Mondavi, Reserve To Kalon, Fume Blanc': '$37',
               'Robert Mondavi, Fume Blanc': '$15.50',
               'Robert Mondavi, Carneros, Pinot Noir Reserve': '$52',
               'Robert Mondavi, Carneros, Chardonnay Reserve': '$40',
               'Robert Mondavi, Carneros, Cabernet Sauvignon': '$48',
               'Robert Mondavi, Oakville, Cabernet Franc': '$48',
               'Robert Mondavi, The Estates, Oakville, Cabernet Sauvignon': '$52',
               'Robert Mondavi, The Estates, Oakville, BDX': '$52',
               "Robert Mondavi, Moscato d'Oro": '$40',
               'Robert Mondavi, Stags Leap District, Cabernet Sauvignon': '$27',
               'Robert Mondavi, Vine Hill Ranch, Cabernet Sauvignon': '$113',
               'Schrader, CCS Beckstoffer To Kalon, Cabernet Sauvignon': '$335',
               'Schrader, GIII Beckstoffer Georges III, Cabernet Sauvignon': '$310',
               'Schrader, RBS Beckstoffer To Kalon, Cabernet Sauvignon': '$335',
               'Schrader, T6 Beckstoffer To Kalon, Cabernet Sauvignon': '$310',
               'Schrader, Beckstoffer To Kalon, Cabernet Sauvignon': '$310',
               'Schrader, MB Beckstoffer To Kalon, Cabernet Sauvignon': '$310',
               'Schrader, Old Sparky, Cabernet Sauvignon': '$310',
               'Schrader, Beckstoffer Las Piedras, Cabernet Sauvignon': '$310',
               'Schrader, LPV Beckstoffer Las Piedras Vineyard, Cabernet Sauvignon': '$310',
               'Schrader, Heritage Clone To Kalon, Cabernet Sauvignon': '$335',
               'Schrader, NI': '$310',
               'Schrader, WH Wappo Hill Vineyard, Cabernet Sauvignon': '$335',
               'Schrader, Colesworthy, Cabernet Sauvignon': '$310',
               'Schrader, Boars View, Chardonnay': '$310',
               'Double Diamond, Napa Valley': '$53',
               'Double Diamond, Oakville, Napa Valley': '$53',
               'Double Diamond, Mayacamas': '$53'}

guidance500ml = {"Robert Mondavi, Mosacto d'Oro": '$12'}

guidance375ml = {'The Prisoner, Cabernet Sauvignon': '$21',
               'The Prisoner, Chardonnay': '$15',
               'The Prisoner, Saldo, Zinfandel': '$13',
               'The Prisoner': '$20',
               'The Prisoner, Blindfold': '$15',
               'The Prisoner, Blindfold, White': '$15',
               'The Prisoner, Red Blend': '$20',
               'The Prisoner, Unshackled, Chardonnay': '$15',
               'Ruffino, Chianti Classico, Riserva Ducale': '$6.75',
               'Ruffino, Il Ducale': '$12.25',
               'Ruffino, Modus': '$11',
               'Robert Mondavi, Napa, Chardonnay': '$11',
               'Robert Mondavi, Napa, Merlot': '$12',
               'Robert Mondavi, Napa, Cabernet Sauvignon': '$14',
               "Robert Mondavi, Moscato d'Oro": '$26',
               'Schrader, CCS Beckstoffer To Kalon, Cabernet Sauvignon': '$160',
               'Schrader, RBS Beckstoffer To Kalon, Cabernet Sauvignon': '$160',
               'Schrader, GIII Beckstoffer Georges III, Cabernet Sauvignon': '$160',
               'Schrader, Beckstoffer To Kalon, Cabernet Sauvignon': '$160',
               'Schrader, T6 Beckstoffer To Kalon, Cabernet Sauvignon': '$160',
               'Double Diamond, Oakville, Napa Valley': '$32'}

guidanceBTG = {'The Prisoner': '$17',
               'The Prisoner, Saldo, Zinfandel': '$11',
               'The Prisoner, Red Blend': '$17',
               'The Prisoner, Unshackled, Chardonnay': '$13',
               'The Prisoner, Unshackled, Cabernet Sauvignon': '$13',
               'The Prisoner, Blindfold, White': '$17',
               'The Prisoner, Cabernet Sauvignon': '$31',
               'The Prisoner, Blindfold': '$18',
               'The Prisoner, Chardonnay': '$22',
               'Ruffino, Modus': '$7',
               'Ruffino, Chianti Classico, Riserva Ducale': '$6',
               'Ruffino, Romitorio Santedame': '$45',
               'Ruffino, Il Ducale': '$11',
               'Ruffino, Toscana cabreo Borgo': '$8',
               'Robert Mondavi, Napa, Cabernet Sauvignon': '$12',
               'Robert Mondavi, Napa, Merlot': '$22',
               'Robert Mondavi, Napa, Pinot noir': '$22',
               'Robert Mondavi, Napa, Chardonnay': '$18',
               'Robert Mondavi, Carneros, Pinot Noir Reserve': '$22',
               'Robert Mondavi, Carneros, Cabernet Sauvignon': '$12',
               'Robert Mondavi, Fume Blanc': '$20',
               "Robert Mondavi, Moscato d'Oro": '$13',
               'Robert Mondavi, The Estates, Oakville, Cabernet Sauvignon': '$48',
               'Robert Mondavi, The Estates, Oakville, BDX': '$48',
               'Robert Mondavi, Reserve To Kalon, Cabernet Sauvignon': '$113',
               'Schrader, RBS Beckstoffer To Kalon, Cabernet Sauvignon': '$335',
               'Schrader, NI': '$310',
               'Double Diamond, Napa Valley': '$32',
               'Double Diamond, Oakville, Napa Valley': '$32'}
